# Generated by Django 4.0.4 on 2022-05-04 13:24

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('categorie', models.CharField(max_length=200)),
                ('media', models.FileField(upload_to=posts.models.load_media)),
                ('description', models.TextField(max_length=500, null=True)),
            ],
        ),
    ]
