# Generated by Django 4.0.4 on 2022-05-04 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='etudiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.etudiant'),
        ),
        migrations.AddField(
            model_name='projet',
            name='investisseur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.investisseur'),
        ),
    ]
