# Generated by Django 4.0.4 on 2022-05-04 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email adress')),
                ('username', models.CharField(blank=True, max_length=255)),
                ('first_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('ville', models.CharField(max_length=200, null=True)),
                ('photo_profile', models.ImageField(blank=True, upload_to=users.models.load_image, verbose_name='Profile')),
                ('tel', models.IntegerField(verbose_name='telephone')),
                ('type_user', models.CharField(choices=[('Investisseur', 'Investisseur'), ('Etudiant', 'Etudiant')], default='Etudiant', max_length=20, null=True, verbose_name='type user')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('niveauEtude', models.CharField(choices=[('Licence 1', 'Licence 1'), ('Licence 2', 'Licence 2'), ('Licence 3', 'Licence 3'), ('Master I', 'Master I'), ('Master II', 'Master II'), ('Doctorant', 'Doctorant')], default='Licence 1', max_length=30, verbose_name="Niveau D'Etude")),
                ('universite', models.CharField(max_length=100)),
                ('fiche_inscription', models.FileField(upload_to=users.models.load_image)),
                ('bio', models.TextField(max_length=500, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('users.utilisateur',),
        ),
        migrations.CreateModel(
            name='Investisseur',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('profession', models.CharField(max_length=70)),
                ('entreprise', models.CharField(max_length=100)),
                ('objectif', models.CharField(max_length=500)),
                ('etudiant', models.ManyToManyField(blank=True, related_name='investisseurs', to='users.etudiant')),
            ],
            options={
                'abstract': False,
            },
            bases=('users.utilisateur',),
        ),
    ]
